# ---------- build ----------
FROM golang:1.25-alpine AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /out/mc-worker ./cmd/worker

# ---------- runtime ----------
FROM gcr.io/distroless/static:nonroot
WORKDIR /
COPY --from=builder /out/mc-worker /mc-worker
USER nonroot:nonroot
ENTRYPOINT ["/mc-worker"]

