FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/mc-worker ./cmd/mc-worker
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/mc-pull-worker ./cmd/mc-pull-worker

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/mc-worker /mc-worker
COPY --from=build /out/mc-pull-worker /mc-pull-worker
USER nonroot:nonroot
ENTRYPOINT ["/mc-pull-worker"]