FROM golang:1.25 AS build
WORKDIR /src
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /out/mc-dispatcher ./cmd/mc-dispatcher

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/mc-dispatcher /mc-dispatcher
USER nonroot:nonroot
ENTRYPOINT ["/mc-dispatcher"]